[package]
name = "sudoku-web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = { workspace = true }
sudoku = { path = "../sudoku" }

[profile.release]
opt-level = "s"
